# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
language: r
r: bioc-devel
sudo: true
cache: packages
warnings_are_errors: false

bioc_required: true
bioc_use_devel: true
use_bioc: true

